### PR TITLE
Extended HG.GeneralSerializer.StringSerializer support

### PR DESCRIPTION
**Pull request by Nebby1999**
The ``HG.GeneralSerializer.StringSerializer`` is a class used mainly for Serializing data into Strings.

This class is mainly used by the EntityStateConfiguration system and the EntityStateCatalog, outside of regular VS mods which set the entity state fields directly via code, Thunderkit made mods utilize the EntityStateConfiguration class. this class, as the name suggests, its used to configure an EntityState's Static and Instance fields.

While greatly useful, the StringSerializer doesnt serialize Types other than the ones it has, and in my opinion, having extra serializers could be extremely useful in the long run for mods that use the StringSerializer in EntityStateConfiguration or in other ways.

This is why i decided to create a class that could extend the functionality of the StringSerializer by hookingg it's methods, this new class adds the following SerializationHandlers for the following types:

* LayerMask
* Vector4
* Rect
* RectInt
* char
* Bounds
* BoundsInt
* Quaternion
* Vector2Int
* Vector3Int
* Any enum.

I was debating originally wether or not this should belong on the bepinexpack, or as a regular R2API submodule, however, under the pretense of the existence of other classes which add QOL elements for developers. I've decided to should be in BepinexPack so everyone can recieve the improvements this provides.

The posibilities of this PR are already implemented on RoR2EK's Indev master. where it can now use Enums, Bounds and More.
image

### CODE REVIEW

**Comment by Nebby1999** [comment]
Not exactly runtime related, but i've already used the features in this PR to fully implement these new serialization options into the up and coming EditorSetting revamp for RoR2EditorKit, including all these new goodies for the MapNode placer.
image

**Comment by xiaoxiao921** [comment]
So unless I'm missing something someone need to implement the corresponding tools in the editor so that this PR can be used?

**Comment by Nebby1999** [comment]
> So unless I'm missing something someone need to implement the corresponding tools in the editor so that this PR can be used?

Technically speaking yes. however, these aforementioned tools are already implemented on R2EK's side.

Given the nature of how ECS works, you still need an Editor to make the experience of working with it pleasurable, otherwise it becomes a dizzying nightmare of nested fields within fields., the picture of the original post of the PR shows these fields working inside an ECS using the Inspector ror2ek provides.

**Comment by xiaoxiao921** [comment]
i'm a bit hesitant to merge this in this repo as it seems more like a feature set for editor workflow than really something that attempt to fix something that the game does wrong in the first place that hinder modding.

**Comment by Nebby1999** [comment]
> i'm a bit hesitant to merge this in this repo as it seems more like a feature set for editor workflow than really something that attempt to fix something that the game does wrong in the first place that hinder modding.

its indeed not something that the game does "wrong" persay, the serializer by itself works just fine as it is, my intention with this increased serialization posibilities was to ensure better ways to configure the behaviour of custom entity states.

Serializing something like enums for special, in state behaviours is a bit more difficult for example, Serializing enums is not possible under the default game, so you can either:

a. Serialize the enums manually as a numerical value, and then utilize casting to cast into the enum
b. Serialize the enum manually using the enum name, and then deserialize manually using Enum.Parse

This is an issue, as either way can be prone to failure due to the nature of not knowing exactly the values at the top of someone's head. one of the Starstorm events are forced to serialize enums using strings to determine how close a nemesis spawn should happen (IE: DirectorPlacementRule.PlacementMode).

While its true that the ECS system is basically not used by code mods and mainly used for editor based mods, i do believe having these serialization options could be useful regardless, as you could still use the StringSerializer system to serialize other types of data if need be. Even if this benefits more editor based mods, i cant bundle the feature directly into ror2ek as i cannot allow runtime features to be needed for R2EK features to work correctly

(Keep in mind, the extra serializable types in the ECS are only enabled right now if the bepinexpack is found in the editor using preprocessor directives)

**Comment by harbingerofme** [comment]
I think this is better as a feature in r2api editor extensions

**Comment by Nebby1999** [comment]
Closing this as we've talked this should belong more in r2api than in bepinexpack.

**Pull request closed without merging**
